spring:
  datasource:
    url: jdbc:mysql://localhost:3306/booklib?useUnicode=true&serverTimezone=UTC
    username: root
    password: Qazwsx150508
  jpa:
    hibernate:
      ddl-auto: create

someParameter:
  value: 5463